### ISSUE TITLE
Severity Filtering

### ISSUE THREAD

**Issue by brigsz** [agrc/Crash-web#11] opened 2015-02-13 19:56 UTC
As a public user I want an advanced filter for injury or death.
1. `No Injuries`
2. `Injuries`
3. `Fatal`

**Comment by steveoh** [comment] 2015-02-17 20:58
I do not think the data supports this. If it does, please provide the values for each of the 3 categories.

**Comment by steveoh** [comment] 2015-02-18 19:41
this is also a duplicate of #3 . Which one do you want to close?

**Comment by brigsz** [comment] 2015-04-02 20:17
The Severity Filtering should be as follows;
1. `No Injuries`
2. `Injuries`
3. `Fatal`

**Comment by steveoh** [comment] 2015-04-02 20:37
@brigsz what does that clarify?

**Comment by brigsz** [comment] 2015-04-02 20:40
Sounds like we are not on the same page....and we are both unsure what the other is talking about.  Monday....

**Comment by steveoh** [comment] 2015-04-02 20:46
The data contains 
- NULL
- Incapacitating Injury
- No Injury/PDO
- Non-Incapacitating Injury
- Possible Injury

Please map these to `No Injuries`, `Injuries`, and `Fatal`

**Comment by brigsz** [comment] 2015-04-02 21:45
I am speaking with UHP on this.  NULLs cannot be included as they are no data.  
1. Incapacitating Injury - `Injuries`
2. No Injury/PDO - `No Injuries`
3. Non-Incapacitating Injury - `Injuries`
4. Possible Injury -`Injuries`

I wonder if your data source is appropriate and wonder if the table _crash_rollups_ is a better source for `Fatal` and possibly a better source for `Injuries` though it would need a crosswalk. I have sent off an email to UHP folks.  It seems like `Fatal` is being dropped somewhere between UHP and UDOT

**Comment by steveoh** [comment] 2015-04-02 21:59
What field in the rollups table talks about fatal and injuries?

**Comment by brigsz** [comment] 2015-04-02 22:06
In  **crash_rollups**

`NUMBER_FATALITIES`
`NUMBER_FOUR_INJURIES`
ETC TO `NUMBER_ONE_INJURIES`  

I am unsure what the `number_four_injuries` to `number_one_injuries` really represents.

**Comment by steveoh** [comment] 2015-04-22 13:42
No Injury    = Severity ID: 1 = NUMBER_ONE_INJURIES(count)
Possible Injury    = Severity ID: 2 = NUMBER_TWO_INJURIES(count)
Non-Incapacitating Injury    = Severity ID: 3 = NUMBER_THREE_INJURIES(count)
Incapacitating Injury    = Severity ID: 4 = NUMBER_FOUR_INJURIES(count)
Fatal =    Severity ID: 5 = NUMBER_FATALITIES(count)

After looking at the data, I think the crash_rollups table would be best to use. This way we can display the number of injuries/fatalities per accident.

**Comment by brigsz** [comment] 2015-04-22 21:12
This filter appears not to be working. I don't see the changes reflected on the map when I vary my selection

**Comment by steveoh** [comment] 2015-04-22 21:55
that's why it is still open :+1:

**Comment by steveoh** [comment] 2015-05-11 23:53
I do not see those fields in `20XX_Rollups.csv`. Are `NUMBER_FATALITIES` etc in a private location?

**Comment by brigsz** [comment] 2015-05-12 15:25
I have sent out an email on this issue.  I don't think UDOT and UHP are on the same page with what has been made available to AGRC from Scott Jones of UDOT.  It is the crash.csv that holds the severity id which if equals a 5 is represents a fatality, but we don't have a way to know how many fatalities per accident.

**Closed as completed** 2015-05-19 18:03 UTC
